apiVersion: v2
name: vector-agent
type: application
icon: https://vector.dev/press/vector-icon.svg
description: A Helm chart to collect Kubernetes logs with Vector
version: "0.11.0"
appVersion: "0.11.0"
home: https://vector.dev/
sources:
  - https://github.com/timberio/vector/
maintainers:
  - name: Vector Contributors
    email: vector@timber.io
dependencies:
  - name: vector-shared
    version: "*"
    repository: file://../vector-shared
