{{- if .Values.global.networkPolicyEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "kube-state-metrics.fullname" . }}
  namespace: {{ template "kube-state-metrics.namespace" . }}
  labels: {{ include "kube-state-metrics.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels: {{ include "kube-state-metrics.matchLabels" . | indent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - {}
{{- end }}
