{{- if .Values.global.networkPolicyEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{ include "matchLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector: {}
      ports:
      - protocol: TCP
        port: 8080
  egress:
  - {}
{{- end }}
