{{- if .Values.prometheusOperator.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
{{- if .Values.global.serviceMonitor.labels }}
{{ toYaml .Values.global.serviceMonitor.labels | indent 4}}
{{- end }}
spec:
  endpoints:
  - port: http
    honorLabels: true
    {{- if .Values.prometheusOperator.serviceMonitor.interval }}
    interval: {{ .Values.prometheusOperator.serviceMonitor.interval }}
    {{- end }}
{{- if .Values.prometheusOperator.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.prometheusOperator.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.prometheusOperator.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.prometheusOperator.serviceMonitor.relabelings | indent 6 }}
{{- end }}
  selector:
    matchLabels: {{ include "matchLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ printf "%s" (.Release.Namespace) | quote }}
{{- end }}
