{{- if .Values.prometheusOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "labels" . | nindent 4 }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
